const { Mwn } = require("mwn");
const credentials = require("./password.json"/* Local file */);
let pagesList = [];
const fs = require("node:fs");
const readline = require("readline");
let { colours, weapons, legends } = require("./patterns.json");

readline.emitKeypressEvents(process.stdin);

if (process.stdin.isTTY)
    process.stdin.setRawMode(true);

console.log("press q to exit, or any key to print log")

process.stdin.on("keypress", (chunk, key) => {
  if(key && key.name == "q"){
	console.log('"q" received; Exiting');
    exit();
  }
});

let interval,
	done = [];

function exit(){
	clearInterval(interval)
	fs.writeFileSync("done.log", JSON.stringify(done))
	process.exit()
}

function sortAndJoin(aset){
	return [...aset].sort().join("\n")
}

function sleep(ms) {
	return new Promise(resolve => setTimeout(resolve, ms, "sleep"));
}

void async function(){
	console.log("Logging in")

	const bot = await Mwn.init({
		apiUrl: "https://brawlhalla.wiki.gg/api.php",
	
		...credentials,
	
		defaultParams: {
			assert: "user" // ensure we're logged in
		}
	});

	console.log("Logged in")

	console.log("Enabling Emergency Shutoff")
	await bot.enableEmergencyShutoff({
		// The name of the page to check
		page: "User:VALKRI_Mk_2/shutoff",
	
		// check shutoff page every 5 seconds
		intervalDuration: 5000,
		
		// function to determine whether the bot should continue to run or not
		// If returns true, the bot continues to run. Else, onShutoff is called
		condition: (pagetext) => pagetext.length > 2,
		
		// function to trigger when shutoff is activated
		onShutoff: (_pagetext) => {
			console.log("Emergency Shutoff Triggered; Stopping")
			exit()
		}
	});
	console.log("Emergency Shutoff activated")

	const pagesPurge = [
		"Pristine Cutlass",
		"Lighted Eminence",
		"Asgardian Blasters",
		"Crescent Moon Claws",
		"Lucky Magi ☆ Sparkling Sword",
		"Golem's Heart",
		"Rank Breaker",
		"Termin-gator Onyx",
		"Nidhogg Nai",
		"Lawbreakers",
		"Adjudicator's Mercy",
		"Flames of the Furnace",
		"Stake Driver",
		"Leonardo",
		"Curved Beam",
		"Cloud Kickers",
		"Nutcracker Val",
		"Shovel Blade",
		"Dwarven-Forged Lance",
		"Beach Bash",
		"Breezy Magi ☆ Skyward Strikers",
		"Fruitcake",
		"Lion's Pride",
		"Commander Xull",
		"Diamond Cutter",
		"Ironcaster",
		"Signal Flares",
		"Mad Doctor Ulgrim",
		"Apex Predator Asuri",
		"Electronicore Axe",
		"Chimera Val",
		"Museum-Quality Spear",
		"Haunted Incisor",
		"Hunter's Reach",
		"Spear of the Future",
		"Winged Danger",
		"Asgardian Gauntlets",
		"Plasma Cannon",
		"Automatons",
		"The Devourers",
		"Petra Reanimated",
		"Equalizer",
		"Diabolical Doll Arcadia",
		"Giants' Bane",
		"Laughing Dragon",
		"Spark of Madness",
		"Thresher",
		"Atlantean Power",
		"Demon Ogre Koji",
		"King Roland",
		"Freestyle Mirage",
		"Spirit's Passing",
		"Ol' Faithful",
		"Daimio",
		"Dwarven-Forged Spear",
		"Poison Dart",
		"Red Romance Volkov",
		"Jurassic Gnash",
		"Highland Hammer",
		"Starforged Spear",
		"Lin Fei",
		"Dwarven-Forged Greatsword",
		"Barraza",
		"Lacrosse Check",
		"Apple of Eden",
		"Martial Staff",
		"Inscription",
		"Death Rattle",
		"Asgardian Battle Boots",
		"Wooden Knuckles",
		"Martial Fists",
		"Pig Sticker",
		"Iron Mallet",
		"Peppermint Piercer",
		"Vengeance",
		"THNX Researcher Loki",
		"Brass Knuckles",
		"Cyber Myk Shanks",
		"Mythic Hero Val",
		"Boomers",
		"RGB Katars",
		"Electro Overdrive",
		"Weero Wings",
		"Singularity Sickle",
		"The Smackdown",
		"Pearl",
		"Santa's Sleigh-er",
		"Glory of the Lions",
		"Skullcracker",
		"Prizefighter Cross",
		"Orc Raider Jhala",
		"Celestial Ragnir",
		"Fisticuff-links",
		"Asgardian Lance",
		"Borealis Bow",
		"Primordial Punch-Out",
		"Chompers",
		"Smoldering Skewers",
		"High Tide",
		"Fists of the Constellations",
		"The Roadhogs",
		"Clearly a Sword",
		"Double Dragons",
		"Blossom Boom",
		"Piece of Eden",
		"Xull",
		"Broad Sword",
		"World Champion Lance",
		"Trials of Worth",
		"Icy Slicers",
		"Bitpunk Cassidy",
		"Darkheart Geode",
		"Annihilator Azoth",
		"Eclipsers",
		"The Cleaner",
		"Sword of Swords",
		"Budding Blasters",
		"Nightmare Talons",
		"Cho-Kor-late",
		"Splish & Splash",
		"Night Terrors",
		"Orion For Hire",
		"Ember",
		"A Shot at Love",
		"Val",
		"Trench Cutters",
		"Essence of Niflheim",
		"Acuity Manifest",
		"Modular Rift Ember",
		"Headmaster Fait",
		"Apollo's Fury",
		"Fangwild's Heart Ember",
		"Kanabo",
		"Pike of the Forgotten",
		"Metadev Asuri",
		"Flint and Tinder",
		"Core Collapse",
		"Nix Couture",
		"Serpent Spear",
		"Dark Thorn Cleaver",
		"Asuka",
		"Hunting Spear",
		"Reindeer Games Gnash",
		"Cyber Myk Megaboots",
		"Powersurge",
		"Footbrawlers",
		"Bitten Diana",
		"Nightmare Reaper",
		"A Sign from Above",
		"Recurve Bow",
		"Hunter's Pride",
		"Tyr's Fists",
		"Street Race Artemis",
		"Death Awaits",
		"The Breakdown",
		"Rippers",
		"Talon's Edge",
		"Tusk",
		"Jhala",
		"Monstrous Aura",
		"Yokai's Spirit",
		"Secret Admirer Zariel",
		"Nightshade Ragnir",
		"Rhapsody's Edge",
		"Justice Bolt",
		"Fusion Blade",
		"The Korinthian",
		"Hands of the Cosmos",
		"Heaven's Touch",
		"Origin Axe",
		"The Obol",
		"World Cleaver",
		"Saint Nicks",
		"Enchantress",
		"Standard Issue",
		"Nightfall",
		"Great Bite Shark",
		"Riptide Petra",
		"Werewolf Thatch",
		"Lost World Petra",
		"Winged Glory",
		"Ensnaring Boom",
		"Chrometooth Gnash",
		"Leonidas Onyx",
		"Gauntlets of Dexterity",
		"Fossil Fury",
		"Venom of Eba",
		"Astroblade",
		"Black Diamond Mordex",
		"Yari",
		"The Furnace",
		"Runewood Bow",
		"Thor",
		"Devil Jin's Bow",
		"Bödvar",
		"Golden Force",
		"The Monarchy",
		"Famished Beast Barraza",
		"Manhandle Slam",
		"Powerplay Blasters",
		"Uraeus' Fang",
		"Pool Party Diana",
		"Hyper Cleave",
		"Puella Papilio Scarlet",
		"Spine-Chilling Fists",
		"Razor's Reach",
		"Vixen Ada",
		"Sky Captain Scarlet",
		"Gold-Inlaid Bow",
		"Thistle's Flight",
		"Judgement",
		"Royal Crescent",
		"Raven Shaman Dusk",
		"Snake Eyes (Weapon Skin)",
		"Fire Fangs",
		"Looter's Lute",
		"Secret Santa Thatch",
		"Akuma",
		"Grisly Burrs",
		"Cockatiel Munin",
		"Fettered Rage",
		"KaTR-808",
		"Shovel Knight",
		"Vraxxy Jones",
		"Cyber Myk Bow",
		"Amethyst",
		"Mk1 Cannon",
		"Dawn Bringers",
		"Malady Wear",
		"Ken",
		"Marks the Spot",
		"Royal Decree",
		"Selenite Jet Lance",
		"Ornate Anchor",
		"Immortal Caspian",
		"Apocalypse Mirage",
		"Erudition's Call",
		"The Monster Slash",
		"Soulbound Onyx",
		"Ice Fishing",
		"Darkheart Missile",
		"The Frozen Cutlass",
		"Shadow Trawl",
		"RGB Gauntlets",
		"Asgardian Spear",
		"Ghost and Goblin",
		"Wyrmslayer Diana",
		"Master Blacksmith Ulgrim",
		"Lord Vraxx",
		"Reactor Core",
		"Sidewinder Hattori",
		"Shadow Edge",
		"Jaws of the Oni",
		"Gridrunner Thea",
		"Viper's Venom",
		"Starlet Munin",
		"Iron Legion Teros",
		"Valorous Charge",
		"Horror & Fright",
		"Bellow's Breath",
		"Lady of the Dead Nai",
		"Orma",
		"Five-Sevens",
		"Silvermane Gnash",
		"Empress Nai",
		"Nightwatch Sentinel",
		"Prideful Roar",
		"Las Viudas",
		"Demon's Malice",
		"Imperial Star Lance",
		"Frosty's Fury",
		"The Talisman",
		"Razorback Barraza",
		"Classy Roland",
		"Yoshimitsu's Blade",
		"0RC4-M4k0",
		"Sealed Infernum",
		"Aces High Caspian",
		"The Blackhearts",
		"Teacher's Pets",
		"Cú Sídhe Sentinel",
		"Azoth",
		"Flintlock Claws",
		"Sacred Orders",
		"Spinal Sickle",
		"Raptor, the Betrayer",
		"RGB Spear",
		"Back Alley Justice",
		"Boarding Cutlass",
		"Globox",
		"Rail Hammer",
		"Smooth Waves",
		"The Iron Barrel",
		"Inari Yumiko",
		"Immortal Pike",
		"Demonic Wings",
		"Mastercraft Recurve",
		"Chicago Typewriters",
		"The Signature",
		"Numeric Flux",
		"Darkshooters",
		"Lion Rampant Roland",
		"Gift Giver",
		"Dark Matter Vraxx",
		"Pavo Beak",
		"Close Quarters",
		"Splitter",
		"Emperor's Own Blasters",
		"Starved Scavengers",
		"Aqua Blasters",
		"Surprise!",
		"Snowsmoke",
		"Hussar's Prize",
		"Candy Caliber",
		"Long Tooth",
		"Argo's Cannon",
		"Asgardian Sword",
		"Snowman Kor",
		"Specter Spear",
		"Akuma no Kogo Hattori",
		"Ember the Hunter",
		"Biotec-X Scalpels",
		"Mako",
		"Dragonslayer Val",
		"Black Knight",
		"Jiro",
		"Ferrymoth Reno",
		"Apocalypse Hands",
		"Arctic Edge Spear",
		"Stryge",
		"Jiro the Specialist",
		"Executive Order",
		"LOL RIP",
		"God Tyr",
		"Laughing Stock",
		"Rocker Volkov",
		"Leash of Souls",
		"Photon Sphere",
		"Atlantean Orion",
		"The Miracle Workers",
		"Devil Cross",
		"Feather's Edge",
		"Ronin Koji",
		"Spitebringer",
		"Rocket Powered Warhorse",
		"High Frequency Yumiko",
		"Pizza Punchers",
		"Steven's Shields",
		"Trueflight",
		"Valkyrie's Fury",
		"Bushwacker Blades",
		"Warrior's Pride",
		"Nightmare Slicers",
		"Bump in the Night",
		"Galactic Glitch",
		"Beowulf Crushers",
		"Asgardian Cannon",
		"Earth Gauntlets",
		"Dark Scarabs",
		"Krusty Krab Spatula",
		"Whistling Death",
		"Witchfire Brynn",
		"Soldier's Duty",
		"Piercing Poison",
		"Fiendish Knight Roland",
		"Darkheart Blade",
		"Luke",
		"Spear of Mercy",
		"Flight Plan",
		"Darkheart Orb",
		"Gauntlets of Belzar",
		"Great Khopesh",
		"Coastline Pulse",
		"Atlantean Ada",
		"Eliminator Nix",
		"Rabbid Boppers",
		"Swim Team Mako",
		"Twirling Flourish",
		"Chun-Li",
		"Fiendish Slice",
		"Yokai Slam",
		"Sword of Mercy",
		"Righteous Indignation",
		"Interface",
		"Darkheart Claymore",
		"Eternal Skyrocket",
		"RGB Axe",
		"Merrow Sidra",
		"Dimensional Divide",
		"Disco Brawl",
		"Lethal Edge",
		"Victory Rush",
		"Saber of Order",
		"Chi Stopper",
		"White Fang Gnash",
		"Shogun Jiro",
		"Coral Carver",
		"Metadev Val",
		"Dwarven Awl",
		"Raymesis",
		"Lucille",
		"Dragon's Breath",
		"Shredder",
		"Werebat Ragnir",
		"Concrete Slam",
		"Boom Booms",
		"Nunchaku",
		"Tines of the Heart",
		"Winter's Grasp",
		"Crystal Shards",
		"Ornate Scissorblade",
		"Warborn Ulgrim",
		"Helios Reign",
		"Modern Thunder",
		"Nevermore",
		"Pirate Queen Sidra",
		"Twin Sai",
		"Null Pointer",
		"Riddle of Strength",
		"Red Raptor",
		"Imperial Decree",
		"Deadly Shoku",
		"Lord's Justice",
		"Soul Battery",
		"Battle Axe",
		"Grueling Terror",
		"Divine Intervention",
		"Outrun",
		"Nanometal Spear",
		"Flora Blades",
		"Xavier Woods",
		"Menace Maul",
		"Devil Jin",
		"Anubis Mirage",
		"Royal Allegiance",
		"Biker Thatch",
		"Shriek & Wail",
		"Hardlight Greatsword",
		"Cyber Myk Pike",
		"Numbskull",
		"Perfect Wu Shang",
		"Thermal Runaway",
		"Lockdown Nix",
		"Barbaraxe",
		"Fortune Hunter Caspian",
		"Darkheart Crusher",
		"Ghost Familiar",
		"Sword of the Demon",
		"Cross",
		"Hattori",
		"Ceremonial Axe",
		"Dwarven-Forged Bow",
		"Bass Drop",
		"Darkheart Artemis",
		"Dwarven-Forged Orb",
		"Dark Conjurers",
		"Gentleman Wu Shang",
		"Nightmare Eye",
		"Suitor Lucien",
		"Gatekeeper Teros",
		"Palette Knife",
		"Cinderguard Thor",
		"Sir Rayelot",
		"Old School Spear",
		"King Knight",
		"Pharaoh King Magyar",
		"Actuator Claws",
		"Beta Thrusters",
		"Terrorbyte",
		"Fait",
		"Hot Lava (Weapon Skin)",
		"Soulmate Azoth",
		"Sol Spear",
		"Wipeout Nix",
		"Poseidon Thatch",
		"Tundra Geir",
		"Asgardian Greatsword",
		"Clamshell Grasp",
		"Flight Risks",
		"Blooming Blade",
		"Fire Hose",
		"Laticauda's Poison",
		"Seraph Artemis",
		"Exalting Spire",
		"Cannon Strike",
		"Matchmaker Vector",
		"Metadev Barraza",
		"SpongeBob SquarePants",
		"Blood Moon Influence",
		"Castaway Thatch",
		"Spring Cleaning",
		"Serape Kid Cassidy",
		"Floral Zephyr",
		"Odin's Spear",
		"Aurora Kaya",
		"Airship Engineer's Hammer",
		"Kabuki Hattori",
		"Cristatus Wingspan",
		"Boss's Judgement",
		"Winged Blade",
		"Wrath of Hel",
		"Orion",
		"Corsair Mirage",
		"Into the Abyss",
		"Asteroid Grinder",
		"The Berserker",
		"Iron Legion Mordex",
		"Forgeheart Teros",
		"Opal's Bow",
		"Huntsman Volkov",
		"Blueprint",
		"Silver and Steel",
		"Kami Bow",
		"Daikama",
		"Dark Shovel Blade",
		"Horseman Lucien",
		"Ritzy Bödvar",
		"Twisted Titanium",
		"Bamboo Staff",
		"Dwarven-Forged Gauntlets",
		"Yataghan Sword",
		"Dragon's Fury",
		"Polar Poleax",
		"Painkiller",
		"Neostreet Hattori",
		"The Cure Seeker",
		"Idle Hands",
		"Prey Catcher",
		"Netherworld Artemis",
		"Sword of Truth",
		"Soulbinder",
		"Date Night Nai",
		"Nightlapse",
		"Starry Scythe",
		"Michelangelo",
		"Frost Tech Sentinel",
		"Yoshimitsu",
		"Heart of Hathor Mirage",
		"H2-KO",
		"Love Hurts",
		"Winter's Grave",
		"Hraesvelgr's Eyes",
		"Battleblades",
		"Classy Thatch",
		"Glory (Weapon Skin)",
		"Laplace's Demon",
		"Demon Bride Hattori",
		"Event Horizon Artemis",
		"Extinction Event",
		"Security Measure",
		"Rising Glory",
		"Queen Nai",
		"Moonbeam Blade",
		"Forerunner",
		"Darkheart Longbow",
		"Swashbuckler Asuri",
		"Stringed Scavenger",
		"Sourcecode Petra",
		"Damascus Cleaver",
		"Mjölnir",
		"SPNKr Rocket Launcher",
		"Zhaktari Issue",
		"End Bringer",
		"Coco-knuckles",
		"Dwarven-Forged Blasters",
		"Power Sword",
		"Meadowguard Ember",
		"Lucien",
		"Asp and Adder",
		"Soul Scourge",
		"Ray of the Dead",
		"Punkin Spice Yumiko",
		"Grass Axe",
		"Kakurenbo",
		"Makin' Bacon Pancakes",
		"Bitter Entities",
		"Verdict",
		"Terror-Watt Xull",
		"Overdrive Lucien",
		"Iron Might",
		"Assassin's Breath",
		"Twin Tails",
		"Kingsblade",
		"Eternal Love Brynn",
		"Eye of the Oni",
		"Harbinger Orion",
		"Runtime",
		"Hand-Saw",
		"Roland the Victorious",
		"Corrupted Blood Tezca",
		"Dragon Axe",
		"Digital Sample",
		"Grim Reaper Nix",
		"God King Teros",
		"Holiday Fear",
		"Seridashi",
		"Frosty Revenge",
		"Autumnal Scepter",
		"1000 Army Cannon",
		"Eye of Horus",
		"Serve & Protect",
		"Forsaken Magyar",
		"Nutsy",
		"Quasar",
		"Drivsnö Pulse",
		"Cthu'shang",
		"Luminary Authority",
		"Judgment Claws",
		"Faithful Departure",
		"Sharktooth Grin",
		"Fire Giant Lance",
		"Cozy Sweater Fait",
		"Specter Knight",
		"Heart of Gold",
		"Catlass",
		"Handcrafted Cannon",
		"Scare-Ware",
		"Rocket Lance of Mercy",
		"Infernal Warlock Volkov",
		"Blooming Dream",
		"Heimdall's Call",
		"Staff Sgt. Cross",
		"Wings of Justice",
		"Plasma Cleaver",
		"Laser Blazers",
		"Skull of the Saint",
		"Villain Monologue",
		"Afterlife",
		"Fangwild Kor",
		"Plastic Pike",
		"Teeth-Grinder",
		"Galactic Gavel",
		"Briar Barbs",
		"Hall Minotaur Teros",
		"Gumshoe Sentinel",
		"Brynn",
		"Dwarven-Forged Axe",
		"Warrior's Wisdom",
		"Seeker Wu Shang",
		"Warrior Spirit Kor",
		"Street Sovereign Petra",
		"Kor",
		"Stardrive",
		"Scarecrow Nix",
		"Dwarven-Forged Scythe",
		"Judge and Jury",
		"Scintilating Spear",
		"John Cena",
		"Sidekick Souvenir Orb",
		"Cosmic Fait",
		"Bone & Bane",
		"The Closer",
		"Ice 'Em",
		"Earthshaker Seismic Sledge",
		"Axe of Mercy",
		"Atomic Orion",
		"Apex Keysword",
		"Ebon Blasters",
		"Heartbleed",
		"Octavius Mordex",
		"Loves Me",
		"Driftwood Chopper",
		"Corinthian Lance",
		"Crimson Cutlass",
		"Lichlord Azoth",
		"Big Dog Blasters",
		"Wraith's Sickle",
		"Date Night Dusk",
		"Nightshade Ember",
		"Shrouded Blade",
		"Soulflame",
		"Regifted Spear",
		"Royal Spoils",
		"Sagittarius Crescent",
		"Brass Section",
		"Primrose Mallet",
		"Princess Bubblegum",
		"Teros",
		"Queen of Scales Jhala",
		"Sweet Magi ☆ Dream Spear",
		"Gilded Glory (Axe Skin)",
		"Panic Maker",
		"Dark Horse",
		"Briar Rose Arcadia",
		"Ymir's Sledge",
		"Jake Fists",
		"Hammer Decorum",
		"Oendan Jiro",
		"Sword of Heroes",
		"Task Force Isaiah",
		"Soul Blasters",
		"Pulaski Pike",
		"Plague Knight",
		"Chaos Harvester",
		"Blaster Pistols",
		"Yokai Naginata",
		"Final Wish",
		"Scrying Glass",
		"Cyber Oni Orion",
		"The Boulders",
		"Aang",
		"Sobek Ragnir",
		"Oni Bite",
		"Benevolent Light",
		"Devil's Maw",
		"The Bolt",
		"Brawl Dad Isaiah",
		"Cull",
		"Toxic Ranseur",
		"Kingpin Scythe",
		"Hound's Fangs",
		"Termidex",
		"Gloryhound",
		"Dark Depths Ragnir",
		"Island Azoth",
		"Watery Grave",
		"Kunoichi Val",
		"Frost Brandr",
		"Fire Nation Spear",
		"Serpent's Fangs",
		"The Albatross",
		"Ambition",
		"Devious Axe",
		"Laser Light Cannon",
		"Jörmungandr Mako",
		"Budding Reunion",
		"Tiercel Orb",
		"Cyber Myk Gauntlets",
		"Plutonium Pike",
		"Chariot Ride",
		"Whispers of the Asp",
		"Connie's Sword",
		"Wraith Barraza",
		"Tezca",
		"Interstellar Rocket",
		"Wu Shang, the Seeker",
		"Steam Tank Scarlet",
		"Brimstone Blasters",
		"Guardian Onyx",
		"Fiendish Fists",
		"Arctic Trapper Xull",
		"Dragon Tooth Katars",
		"Revolving Blades",
		"Baron Azoth",
		"The Steamroller",
		"Wild's Smasher",
		"Nightmare Hatchet",
		"Tooth & Trouble",
		"Space Shooters",
		"Magni",
		"Hugin",
		"Digital Lockdown",
		"Trusty Trowels",
		"Harlequin Caspian",
		"Executioner's Razors",
		"Howlin' Skull",
		"Holly Jolly",
		"Divine Hands",
		"Bogha",
		"Raydvar",
		"Spear of the Nile",
		"The Consequences",
		"Ded.",
		"Thor by the Shore",
		"Hot Choco Orb",
		"Snake Charmer Nai",
		"The Shrine",
		"Madame Yumiko",
		"Mech Makers",
		"Star Guardian Ember",
		"Ground & Pound",
		"Davey Jones' Anchor",
		"Grand Prix",
		"Lil' Yumiko",
		"Coral Spines",
		"Apothecary Mitts",
		"Ice Sickle",
		"Eye of the Storm",
		"Space Dogfighter Vraxx",
		"Kiss of Fire",
		"Seraph's Message",
		"Blazing Light Sword",
		"Phantom Fists",
		"Metadev Fait",
		"Commando Val",
		"Dragon's Fire",
		"Scythe of Mercy",
		"Aesir's Orb",
		"Waveslicer",
		"Sledge Fire",
		"Dragon Spawn Bow",
		"Peacock Artemis",
		"The Frozen Edge",
		"Dragon Scale Katars",
		"Maître d'Hattori",
		"Sunset Axe",
		"Yoga Fists",
		"Bokken",
		"Starship Slice",
		"Retro Reaper Nix",
		"Celebratory Sabre",
		"Axe of the World Eagle",
		"Quarrion Sickle",
		"Hydro-Bow",
		"Nothing Up My Sleeve",
		"Sanguine Flight",
		"Oni no Hattori",
		"Scrapped M.O.U.S.E.R.",
		"Black Icicles",
		"Aethon's Wing",
		"Iron Shackles",
		"Boom Box",
		"Duskblade",
		"Orchard Barrel",
		"Folding Chair",
		"Retrograde Rocket",
		"Tigress",
		"First Edition Sentinel",
		"Sword of Davey Jones",
		"Skyrush",
		"Danish Brick Mortar",
		"Sea Krait Nai",
		"Obake Petra",
		"Orion Prime",
		"Thornwood Dusk",
		"Ranno Wu Shang",
		"Sonic Boom",
		"Destiny",
		"Paci-fists",
		"Hotline Slash",
		"Gauntlets of Mercy",
		"Sawbones",
		"Vanir Guardian Bödvar",
		"Devil's Sight",
		"The Chainsaw",
		"Bane Bringer",
		"The Doctor's Orders",
		"Wrecking Crew",
		"Vector Model 01",
		"Scarabs' Bane",
		"The Slayer",
		"Bop",
		"Relentless Pest Reno",
		"Rose Gold Revolvers",
		"Astro Shard",
		"Kanabo Korosu",
		"Diamond Jack Caspian",
		"Plague Doctor Lucien",
		"Shadowbolt",
		"Synthetic Charge",
		"Cinderguard Brynn",
		"Love Affair",
		"Heavy Chopper",
		"Salvaged Yari",
		"Heartstring",
		"Urban Guardian Zariel",
		"Crimson Poison",
		"Draugr Bödvar",
		"Demon Ogre Xull",
		"Mercy Killers",
		"Hardlight Blasters",
		"Rib Ticklers",
		"Völsung Brynn",
		"Psycho Power Aura",
		"Water Wars Cross",
		"The Final Gift",
		"Shark Heart Barraza",
		"Special Forces",
		"Stone of Malice",
		"Wartusk",
		"Hand of Horus Mirage",
		"Keytar Slash",
		"Solar Flares",
		"Gothic Chic Nix",
		"Trident",
		"Dreamshard",
		"Queen of Demons",
		"Pincer Pike",
		"Metadev Brynn",
		"Dragoon Flintlocks",
		"Muerto Azoth",
		"Bitter End",
		"Dragonport Ulgrim",
		"Flashing Knuckles",
		"Aviator Test Rocket",
		"Ultra-Lance",
		"The Taggers",
		"His Nice Shoes",
		"Butcher's Delight",
		"Glacier Strike",
		"The Playback",
		"Root of the Forest",
		"Yumi",
		"Demon's Blade",
		"Haunting Terrors",
		"Dead or Alive",
		"Surt's Arrow",
		"Magic Bubble Wand",
		"Squadron Strikers",
		"Baleful Greatblade",
		"Silver Sledgehammer",
		"Lockpick",
		"Kaya",
		"Hand Wraps",
		"Soul Cleaver",
		"Wolf's Howl",
		"Flame and Cinder",
		"Loves Me Not",
		"Death Adder Hattori",
		"Red Rose Kaya",
		"Sky Scourge Jhala",
		"Beautiful & Deadly",
		"Penguin's Pummel",
		"Moonlight Meteor",
		"Guiding Spirit",
		"Shieldmaiden Brynn",
		"Yokai Smash",
		"Gravity Hammer",
		"Pew Pew",
		"The Mountain",
		"Goofy Goober Guitar",
		"Sky Piercer",
		"Outlaw Loki",
		"Darkheart Spine",
		"Feline Fait",
		"The Dark Cauldron",
		"DJ Hugin",
		"Aesir Blade",
		"Betrayal",
		"Ragnir the Covetous",
		"El Carnicero",
		"Sword of the Raven",
		"Kingdom Bow",
		"Nightmare Mandible",
		"Cursed Mask Yumiko",
		"Nightmare Bow",
		"Dirt Road Drill",
		"Rocket Raptor",
		"Time is Running (Out)",
		"Flint-Lockers",
		"Asgardian Hammer",
		"Fangs of Woe",
		"Prizewinner",
		"Outerworld Zariel",
		"Railgun",
		"Sekai no Kana",
		"RGB Blasters",
		"Howling Siren",
		"Raven Rogue Lucien",
		"The Neutralizers",
		"Hunter's Tail",
		"Shadowstalker Diana",
		"Barbarian Blade",
		"Infinity Blades",
		"Aurora's Spear",
		"Gloom & Doom",
		"The Hayrider",
		"Winged Solstice",
		"Searing Blade",
		"Sakura",
		"Snow Globe",
		"Frost Guardian Ragnir",
		"Bullet Hail of the King",
		"Toothpick",
		"High-Voltage Rippers",
		"World Ender",
		"New Best Friend",
		"The North Wind",
		"Los Gatos Voladores",
		"Sidearms",
		"The Appointment",
		"Bubonic Blasters",
		"Lara's Bow",
		"Airgliders",
		"Heartthrob",
		"The Herald",
		"Pressure Slicer",
		"Dynasty Ender",
		"Silver Bullets",
		"Conk Shell",
		"Fuselage",
		"Glacier's Grace",
		"Elder Wild Ragnir",
		"Armored Kor",
		"Birdshot",
		"Bengali Claws",
		"Ritual Blade",
		"Smokers Mk. B",
		"Gemini's Wrath",
		"Floral Prayer",
		"Magpie Munin",
		"Forbidden Lamps",
		"Alpine's Ace",
		"Nutcracker Bödvar",
		"Sterling Sledge",
		"Sword of Justice",
		"The Undertaker",
		"Ski Pole",
		"Sleight of Hand",
		"In Health",
		"Eternal Blade",
		"Snowdrift Jaeyun",
		"Nightmare",
		"Skybound",
		"Hattori Hanzo Sword",
		"General Vraxx",
		"Just Dead",
		"The Finisher",
		"Spiteful Scepter",
		"Alucard",
		"New West Cassidy",
		"Precision",
		"Airship Anchor",
		"Watermelon Slice",
		"Tide Turners",
		"Ancient Axe",
		"Barbaric Rage",
		"High-Impact Hammer",
		"Destiny's Way",
		"Flamingo",
		"RGB Sword",
		"Humble Hands",
		"Roland the Hooded",
		"Raging Fists",
		"Dark Elf Flamberge",
		"Royal Roar",
		"Apple of Odin",
		"Divine Conviction",
		"Asgard Bödvar",
		"Wicked Wings",
		"Garnet's Gauntlets",
		"Auditore Blade",
		"The Master Chief",
		"Molten Kor",
		"Flaming Oath",
		"Password Crackers",
		"Blood Moon Volkov",
		"Tengu Koji",
		"Hardsuit Val",
		"The Honorable Sir Roland, Esq.",
		"Tokyo Yumiko",
		"Darkpulse",
		"Bear Claws",
		"Amun-Raza",
		"Seven",
		"Sledge Hammer",
		"Tiburon's Teeth",
		"Future Wave Val",
		"Sunforged Spear",
		"Cyber Myk Starblaze",
		"Disassemblers",
		"New School Jhala",
		"Tai Lung",
		"Darkheart Shredders",
		"Jewel of the Forest",
		"Darkheart Reaper",
		"Hidden Dragon",
		"Ace Spiker Lin Fei",
		"Number 1 Fan",
		"Ocelotl Tezca",
		"Thunder and Clash",
		"Royal Warrior Thor",
		"Sentinel",
		"Taurus Skulls",
		"Bramble",
		"Scythe of the Sands",
		"Hack and Slash",
		"Shinigami Jiro",
		"Vanquisher",
		"Pteranodon Gnash",
		"Metadev Ember",
		"Ada",
		"Piercing Petals",
		"Mouse Trap",
		"Donatello",
		"Fangwild Thorns",
		"Los Volcanes",
		"Deus Ex Machina",
		"Debt Collector",
		"Pillar of the Heavens",
		"Qiang",
		"Corsair Cannon",
		"Stalwart Screech",
		"Dawnwalker Cassidy",
		"Aurora Brynn",
		"Street Samurai Koji",
		"Sleeping Demon",
		"Jar-O-Honey",
		"Drakenfire",
		"Spirit Ash's Fangs",
		"Selenite Ray Guns",
		"Grifball",
		"Cyber Bödvar",
		"Mrs. Fix It",
		"Crowbar",
		"The Insignia",
		"Wings of Liberty",
		"Blue Blossom Blade",
		"Kindergarten Kaya",
		"Starforged Scimitar",
		"Fungal Flourish",
		"Closin' Time",
		"High Noon",
		"Jaguar Paws",
		"Forgotten Bow",
		"Bow of Mercy",
		"Power of Courage",
		"Equine Treads",
		"Emperor Koji",
		"Necromantic Aura",
		"Draugr Thor",
		"Crypto Blade",
		"Cat Burglar Asuri",
		"Jaeyun",
		"Technomancer Ada",
		"Imperial Rocket",
		"Mecha Ragnir",
		"Huntress Kaya",
		"Skel-asuri",
		"Metadev Teros",
		"Crossfader",
		"Door-Buster",
		"Wrought Iron Sword",
		"Broken Crown",
		"Hammer of Mercy",
		"Duty & Sacrifice",
		"Kraken Sidra",
		"Edge Guards",
		"Dullahan Jiro",
		"Skull Saw",
		"Bug Fixers",
		"Sacred Relic",
		"Cyclone Hammer",
		"Bonehead",
		"Metalbender's Mittens",
		"Ancestral Steps",
		"Shadow Spear",
		"Honor's Edge",
		"Purge and Exorcise",
		"Nightmare Claws",
		"Nix",
		"Wasteland Treaders",
		"Iron Steel Claws",
		"Eternal Nightfall",
		"Big Clipper",
		"Arcadia",
		"Mizzenmast",
		"Power of Will",
		"Dog Days Mordex",
		"Pro-Tour Racket",
		"Gridiron Xull",
		"Fallen Brynn",
		"Torchbringer",
		"Boomin' Bark",
		"Tempo and Groove",
		"Aesir-Forged Brynn",
		"Achilles' Loss",
		"Boss Cross",
		"Vraxx the King",
		"Carbon-Steel Knives",
		"Shinobi Sword",
		"Desert Island Blasters",
		"Vector (Weapon Skin)",
		"Equinox Arcadia",
		"Ryu",
		"Lord Sentinel",
		"Final Breath",
		"Shark Attack Thatch",
		"Heatblast",
		"Whitewater Gem",
		"Negan",
		"Silent Night",
		"Mecha Teros",
		"Deathbolt",
		"Varin's Axe",
		"Iron Lady Artemis",
		"Sword of the Creed",
		"Art of War",
		"Sucker Punch",
		"Ares's Might",
		"Drake's Battalion",
		"Seven Secrets Spear",
		"Batavian Diplomacy",
		"Sattelite Smash",
		"Hook Setter",
		"Tundra's Talon",
		"Arched Valor",
		"Kor Wrecking LLC",
		"Tourney Lance",
		"Glimpse of Death",
		"Deep One Azoth",
		"Hands of Fate",
		"Beastmaster Sidra",
		"Dark Elf Blasters",
		"Winged Serpent Nai",
		"Magma Spear",
		"Repeating Crossbows",
		"M. Bison",
		"Crystal Whip Axe",
		"Dueling Broadsword",
		"Withering Scythe",
		"Mad Dog Mordex",
		"Elyria's End",
		"Protect & Serve",
		"Regulus",
		"Wu Shang the Breaker",
		"Moonbeam",
		"Yakuza Koji",
		"Sword Breaker",
		"Silver Age Jhala",
		"Asgardian Scythe",
		"Encyclopedia of Brawl",
		"Enlightened Song",
		"Blossoming Blade",
		"Lost Technology",
		"Katars of the Raven",
		"Brick and Mortar",
		"Cupcake Cassidy",
		"Mad Genius Scarlet",
		"Sakura Strikers",
		"Lethal Lute",
		"Thatch",
		"Atom Smasher",
		"Lobster Lance",
		"Matchlock Spear",
		"Crystal Clutch",
		"Revolver Cannon",
		"The Last Ride",
		"Flamberge's Gale",
		"Heaven Cleaver",
		"Darkheart Stompers",
		"Dreadnought Lucien",
		"High Impact Sentinel",
		"Golden Striker",
		"Antler Strike",
		"Turtle Crossing",
		"Knockouts (Weapon Skin)",
		"Casey's Hockey Stick",
		"Gilded Glory Jaeyun",
		"Double-Action",
		"Eba's Retribution",
		"Wicked Blade",
		"Bovine Skull Mallet",
		"Edge of Twilight",
		"Macho Man",
		"Mudras",
		"Reaping Time",
		"Desperado Reno",
		"Gatekeeper",
		"Great-Pop",
		"Honorbound",
		"Beach King",
		"Loa Bow",
		"Armored Attack Rocket",
		"Chemical V",
		"Blue Virus Volkov",
		"Dark Whispers",
		"Atomic Rocket",
		"Fleur de Bees",
		"Ojiisan Koji",
		"Grilled Smoker",
		"Chel",
		"Dogs of War",
		"Steam Sentry Scarlet",
		"Corsair Orion",
		"Mordex",
		"Hotshot Vector",
		"Facemelter",
		"Dragon Hunter Isaiah",
		"Three Fingered Discount",
		"Sky Pirate Sidra",
		"Imperial Lord Dusk",
		"Hwarang Jaeyun",
		"Brooch Bow",
		"Pavonini Talon",
		"Kah-Rah-Tay Gloves",
		"Katana",
		"Ketchup & Mustard",
		"Talk of the Town Tezca",
		"The Rook",
		"Spring Breeze",
		"Kern Koji",
		"Mammothade Cooler",
		"Hyper Turbo Axe",
		"Marauder Bödvar",
		"Silver Naginata",
		"Sakura Strike",
		"Stormlord Ada",
		"Francesca",
		"Doombringer",
		"Punch-a-tron 5000s",
		"North Wind Mordex",
		"Elvenhollow Xull",
		"Pearl's Spear",
		"Rayman",
		"No Running!",
		"Moskitoes",
		"Be True",
		"Axe of Regrowth",
		"Fuel Rod Cannon",
		"Axe-bladed Multi-Tool",
		"Optimized Odzutsu",
		"Infinite & Absolute",
		"Disc Beatdown",
		"Tomb Tamer Nai",
		"That's A Hammer",
		"Bödvar-mania",
		"Ivy Charger",
		"Sword of Freyr",
		"Lynx Asuri",
		"Star Commander Fait",
		"Wild Hunt",
		"Witching Broom",
		"Wurm Shooters",
		"Blood Shard",
		"Booming Roar",
		"Emerald Raptor",
		"Resonators",
		"Cyber Myk Claymore",
		"Needlers",
		"The Oath",
		"Psychlops",
		"Slasher Barraza",
		"Horned Carver",
		"Throttle",
		"Koji",
		"Darkheart Axe",
		"Dunewalker Mordex",
		"Jupiter Rising",
		"Dual Pistols",
		"Celestial Mordex",
		"Dark Arts Fait",
		"Jolly Ripper",
		"Scarlet",
		"Magyar",
		"Cyber Myk Orb",
		"Everlasting Shot",
		"Ready to Riot Teros",
		"Elvenhollow Magyar",
		"Wyrmseeker",
		"Horn of the Scarab",
		"Throwing Anchor",
		"No One is Ready",
		"Soul Fangs",
		"Devoted Shot",
		"Gear Death Experience",
		"The Conch",
		"Greatsword of Mercy",
		"Becky Lynch",
		"The Allthorn",
		"Frostbitten Justice",
		"Infinite Wu Shang",
		"Ice Crusher",
		"Macho King",
		"Attitude Adjustment",
		"Oni Spear",
		"Squidward's Clarinet",
		"Tide Queen",
		"Bone Shard",
		"Shogun Koji",
		"Face-Beater",
		"Mirage Incarnate",
		"Aetheric Rocket Drill",
		"The Punchlines",
		"Ulgrim",
		"Dark Age Orion",
		"Smasher",
		"Scrapshard",
		"Glacier Gavel",
		"Free Parking",
		"Cyberlink Spear",
		"Wasteland Vraxx",
		"Yard Marker",
		"Finn",
		"Section Zero Isaiah",
		"Soulbane",
		"Typhon",
		"High Noon Cassidy",
		"Femur Flex",
		"The Captain",
		"Gothic Warhammer",
		"Stevonnie",
		"Gungnir",
		"Heartbreaker",
		"Vengeance at Hand",
		"Detention Ada",
		"Glorious Conquest",
		"Mach 25 Thea",
		"Bulwark",
		"Serisage",
		"Sir Roland",
		"Blade of Brutus",
		"Cyber Myk Megacannon",
		"The Axe",
		"Searing Sphere",
		"Truth",
		"In Case of Brawl",
		"Svartalfheim's Caverns",
		"Djinn Wu Shang",
		"Carapace Armored Arcadia",
		"Awakened Asuri",
		"Piña Collider",
		"Twilight's Emissary",
		"Admiral Isaiah",
		"The Hibernator",
		"Messatsu Blade",
		"Devil Jin's Gauntlets",
		"Bolt Blasters",
		"Cassidy",
		"Collision Rocket Fists",
		"Gallowglass Jhala",
		"Light of Truth",
		"Demonkin Diana",
		"Iron Standard",
		"Stargleam Scythe",
		"Love Letter Opener",
		"Ezio",
		"Ground Pounder",
		"Gift of Sojobo",
		"Harvest Sickle",
		"Freelancer",
		"Home Run",
		"Astral Core Ada",
		"Trend Setter",
		"Santa Wu Shang",
		"The Mad King",
		"Tiger's Talwar",
		"Furinkazan Gloves",
		"Badlands Asuri",
		"Vraxx the Viking",
		"Nightmare Launcher",
		"PegaSwift Runners",
		"Widowmaker Reno",
		"Long Sword",
		"Mosaic Maul",
		"Catch and Release",
		"Bear'dvar",
		"Eternal Siege",
		"Wicked Claws",
		"Elven Ranger Diana",
		"Snow Shovel Axe",
		"Boiling Point",
		"Holly Jolly Ember",
		"Finishing Touches",
		"Vive la Révolucien",
		"Kraken's Key",
		"Morning Star",
		"Nettle & Belladonna",
		"Sixshooters",
		"Circuit Breaker",
		"Cobalt Mecha Lance",
		"Katars of Mercy",
		"Pole Position",
		"Spellbreaker Diana",
		"Diana",
		"Sol Smasher",
		"Babe",
		"Fate Cleaver",
		"Righteous Spine",
		"Bear Blade",
		"Vector",
		"Skysworn Oath",
		"MP7s",
		"Righter of Wrongs",
		"The Last Crutch",
		"Barnacle Blasters",
		"Unicorn Stampede",
		"Barbarian Axe",
		"Earthly Answers",
		"Onihashi Steel Blade",
		"Twilight Cleaver",
		"Cardinal Talons",
		"Snake Goddess Nai",
		"Mortal Coil",
		"Wings of Victory",
		"Energy Sword",
		"Barbara",
		"Grand Finale",
		"People's Elbow",
		"Crystalline Blades",
		"Rogue Queen Arcadia",
		"Eldritch Thorn",
		"Dragonsplinter",
		"Six String",
		"Apprentice Ulgrim",
		"First Down",
		"Survivor Lara Croft",
		"Emperor's Claim",
		"Firewalls",
		"Jaguar Claws",
		"Dragon's Heart",
		"Bewitching Scarlet",
		"Anchor Shanks",
		"Wu Shang",
		"Cupid's Bow",
		"Raycasters",
		"Volkov",
		"Foe Splitter",
		"Martial Blades",
		"Sinister Strike",
		"Warlord Jhala",
		"Ice Slicer",
		"M7 SMG & Plasma Rifle",
		"Ashen Ragnir",
		"Steam Faction Scarlet",
		"Pulsing Thicket",
		"Battle Axe (Simon Belmont)",
		"Dusk (Weapon Skin)",
		"Burning Golden Razors",
		"Payday",
		"Astro Slammer",
		"Heart of the Volcano",
		"Spec-Ops Lucien",
		"The Monster Gnash",
		"Mr. Stabby",
		"Special Forces Pistols",
		"Crush Killer",
		"Hippokampos",
		"Teatime Scarlet",
		"Snow Stalker Kaya",
		"Simon Belmont",
		"Spear of the Living",
		"Neon Gleam",
		"Cyber Myk Gavel",
		"Seal Breaker",
		"Nimue",
		"Night Blight",
		"Ivaldi's Wings",
		"The Mittens",
		"Cutting Edge Hattori",
		"White Out Nix",
		"Particle Blade",
		"Equinox Spire",
		"Fisticuffs",
		"Ghoulish Clutches",
		"Calavera Cassidy",
		"Tooth and Nail",
		"Shadow Ops Isaiah",
		"Devilish Spike",
		"Shadaloo Scepter",
		"Asgardian Ezio",
		"Whispering Blade",
		"Heartbreaker Barraza",
		"Refractors",
		"RGB Cannon",
		"I've Got Spirit!",
		"Ragnirsaurus Rex",
		"Permafrost",
		"Love's Embrace",
		"Cupid's Arrow",
		"Manta Blade",
		"Burning Enlightenment",
		"Dynasty and Legacy",
		"Caspian",
		"Champion's Axe",
		"Twin Katanas",
		"Crowned Favor",
		"The Yetee Teros",
		"Phantom of the Armor Magyar",
		"Deadly Diamonds",
		"Patadas Voladoras",
		"Bitrate Blade",
		"Hit Hard",
		"Cold Embrace",
		"Dust Devil Cassidy",
		"Galaxy Lance",
		"Lightning Rod",
		"Despair",
		"Lightning Sigil",
		"Helios' Gems",
		"Rapture",
		"Corrupted Shredders",
		"Soulbound Diana",
		"Glitz & Glam",
		"Dusk",
		"Tactical Sidearms",
		"Mega Wrench",
		"Athena Kaya",
		"Beithir's Breath",
		"Chocolate Cherry Sunburst",
		"Penumbral Crescent",
		"The Heavyweights",
		"The Test",
		"Demonic Slab",
		"Krampus Cross",
		"Whirlwinds",
		"Dessert Eagles",
		"Dueling Pistols",
		"Autumn Wind",
		"Haunted Hook",
		"Rift Dweller Teros",
		"Hand Cannons",
		"Eternal Flame",
		"4LLY",
		"Great-Oar",
		"The Harvester",
		"Flashfire",
		"Deathly Presence Munin",
		"Inferno Ragnir",
		"The Angel",
		"Constellation Carver",
		"Hit Often",
		"Shadowlord Cross",
		"Electro Hammer",
		"Wipeouts",
		"Fatal Error Ada",
		"Dragon Heart Ember",
		"Dawn Hammer",
		"Chopsicle",
		"Zhulong Lin Fei",
		"Foxfire",
		"The Seeker's Spear",
		"Ragnir",
		"Wings of the Sage",
		"The Snowplow",
		"Selena's Smasher",
		"Soul of Aoku",
		"Orb of Mercy",
		"The Gladius",
		"The Hunters",
		"Remnant of Fate",
		"Morning Maul",
		"Revolvers",
		"Festive Yeti Onyx",
		"Onyx",
		"Chitinous Blade",
		"Arcanium Ulgrim",
		"Metadev Bödvar",
		"Hanbok Jaeyun",
		"Luminous Paladin Jaeyun",
		"Golden Saber",
		"Racing Lance",
		"Cannon of Mercy",
		"Desequencers",
		"Arts and Crafts",
		"Clawholds",
		"Ehzot Azoth",
		"Owl's Flight",
		"Emerald Blade",
		"President Sentinel",
		"Swanky Diana",
		"Great Board",
		"Harpy Brynn",
		"Golden Gladiator Magyar",
		"Fenrir Mordex",
		"Sandy Cheeks",
		"Magma Bolt",
		"Caelestis Yumiko",
		"Corsair Sword",
		"Dawn and Dusk",
		"Gruagach",
		"Exquisite Cannons",
		"Piledriver",
		"Mk 1 Lance",
		"Matsuri Yumiko",
		"Dwarven-Forged Sword",
		"Azure",
		"Ranked Ladder",
		"Claideamh",
		"Dragon's Woe",
		"Galaxy X Nai",
		"Infernal Cross",
		"Joint Pain",
		"RGB Boots",
		"The Mark",
		"Monofilament Blade",
		"Po",
		"The Abyss",
		"Pyrois Blast",
		"Splish Splash",
		"Vespian Six Shooter",
		"Love Bug Val",
		"Soul Render",
		"+5 Daggers",
		"Artemis",
		"Showman's Daggers",
		"Steam-Charged Saber",
		"Fallen Raptor",
		"Blasters of Mercy",
		"Garnet",
		"Candy Cane",
		"Dragon Sledge",
		"Roar of the Pride",
		"Scrimshaw Harpoon",
		"Necromancer Azoth",
		"Maple Breeze",
		"Saltwater Saber",
		"Bullet Diver Lucien",
		"Petra",
		"Space Race Cassidy",
		"The Grips",
		"Crystalline Mallet",
		"Rick's Hatchet",
		"Shibuya Recurve",
		"Cat Scratch",
		"Viking's War-axe",
		"Divine Thunderclap",
		"Haunting Blades",
		"Wasteland Ada",
		"The Sequels",
		"Jade Truth",
		"The Phenom",
		"Piercing Regret",
		"War Pipes",
		"Elm Recurve Bow",
		"Fangwild Bow",
		"High Priestess Nai",
		"Green Thumb Lin Fei",
		"Iridium Engine",
		"Yoshimitsu's Scythe",
		"Demon Rider Artemis",
		"Lookin' Sharp",
		"Silent Wings",
		"Komainu Jiro",
		"Snow Shooters",
		"Dragonheart Gauntlets",
		"Mirage the Cleaner",
		"Blade of Shadows",
		"Jellyfishing Net",
		"Bear Arms",
		"XLR8R's",
		"Red-Hot Ranseur",
		"Asgardian Orb",
		"Fate Crusher",
		"Tactical Pistols",
		"Hellhounds",
		"Stained Shards",
		"Sawed-Off Barraza",
		"Moongleam Bow",
		"Wanderer Seven",
		"Outback Gnash",
		"Fu Lion Charm",
		"Sidewinder",
		"Tactical Recurve",
		"Overhand Slicers",
		"The Broken Forge",
		"Fangwild Havoc",
		"Tetramand Beatdown",
		"Mk V Lance",
		"Fu Fists",
		"Switchcomb",
		"Perceptive Flight",
		"Dueling Dukes",
		"Honeybeeno",
		"Star Miner Ulgrim",
		"Zip and Snap",
		"Kabuto Orion",
		"Chrysalis Lance",
		"Counter Curse",
		"The Nautilus",
		"Grovewarden Ember",
		"Nightmare Mauler",
		"Event Horizon",
		"Cursed Gold Thatch",
		"Needle Drop Spear",
		"Lovelaced Ada",
		"Exception Handlers",
		"Cygnus",
		"Olive Stompers",
		"OHHHHH YEEAAAH!",
		"Twin Solstice",
		"Oath of Service",
		"Asgardian Katars",
		"Parasol Pike",
		"Fox Spirit Yumiko",
		"Ultra Oil Lamp",
		"Firefighter Seven",
		"Teeth of the Nile",
		"Divine Question",
		"AG Tactical System",
		"Double Cross",
		"Calaveraxe",
		"Librarian Mirage",
		"Michonne",
		"Eclipse Artemis",
		"Darkheart Blasters",
		"Tinyfigure Seven",
		"Corpse Bride Mirage",
		"Garuda's Core",
		"Vetr Bearded Axe",
		"Plague Boost",
		"Ivaldi Design",
		"Rust",
		"Net Guns",
		"Cursed Bow",
		"Koi Cannon",
		"Mother of Pearl Blasters",
		"Rotten Oar",
		"Valor",
		"Locker Boom",
		"Divine Dragoneers",
		"Death's End",
		"Kingly Lance",
		"Live Action Orion",
		"Revelations Ezio",
		"Darkheart's Grasp",
		"Gorgon Thea",
		"RGB Greatsword",
		"Getaway Points",
		"Rosewood Spear",
		"Slapshot Artemis",
		"Jotun Ulgrim",
		"Match Point Roland",
		"Thunder Bass Blasters",
		"Memento Mori",
		"Dhalsim",
		"Arbiters Reach",
		"Zenith Daggers",
		"Wu Shang Kong",
		"Kukri Carver",
		"Power Flash",
		"Realm Etchers",
		"Eclipsing Faith",
		"Maggie",
		"Gladius Magnus",
		"Ctrl & Delete",
		"Big Rig Bödvar",
		"Snarler",
		"Battle Lance",
		"Law of the Land",
		"Bifrost Edge",
		"Death Throes",
		"RGB Scythe",
		"Death Touch",
		"Deathcap Dusk",
		"Ice Angling",
		"Hyperdrift Vector",
		"Bathyal Blade",
		"The Unblinking",
		"Wreck the Halls Teros",
		"For Royalty",
		"The Starsmasher",
		"Wave Breakers",
		"Binding Chains",
		"Bone Claws",
		"Halo Breakers",
		"Exploding Blades",
		"Mecha Asuri",
		"Archfiend Zariel",
		"Echidna",
		"Nightmare Butcher",
		"Prophecy",
		"Guardian Mallet",
		"The Pale Horse",
		"Loch's Harpoon",
		"Blood Keepsake",
		"In Sickness",
		"Yorishiro",
		"The Rock",
		"Merry Jingle Scythe",
		"Royal Sword",
		"Fighting Spirit Gloves",
		"Kelpie Thea",
		"Shock Katars",
		"Sharkbite",
		"Team Spirit Gnash",
		"Fire & Brimstone",
		"MK Needles",
		"Salty Shooters",
		"Jawbreakers",
		"Goblin Thatch",
		"Wolfsilver Blades",
		"Warhammer",
		"Ice Pick",
		"Guardian's Edge",
		"Uprising",
		"Nina's Daggers",
		"Electrode Guns",
		"Headache",
		"Offworld",
		"Iron Fury",
		"Assassin's Blades",
		"Tamed Beast",
		"Test Legend",
		"Roar & Pounce",
		"Fire & The Flame",
		"Von Evilstein's Heart",
		"Koa Wood Axe",
		"Summer Soaker",
		"Heirloom (Hammer Skin)",
		"Golden Punishment",
		"Star Render",
		"Warchief Bödvar",
		"Axe You Out",
		"The Jade Price",
		"Dragonaut Vector",
		"Rending Talons",
		"The Big Bang",
		"Neutron Maul",
		"Honor Bound Cross",
		"Jade Dragon",
		"Mississippi Wrangler",
		"Compressed Metal Mallet",
		"Last Bite",
		"Destabilizers",
		"Professor Vraxx",
		"Alpine Kaya",
		"Soul Dancer",
		"Nina's Blasters",
		"Corsage Royale",
		"Darkheart Petra",
		"Holy Covenant",
		"Oddball",
		"Heartaches",
		"Archangel Zariel",
		"Crystal Blades",
		"Voice of the Forest",
		"Adrenaline Rush",
		"Carved Precision",
		"Star Merc Val",
		"Nemesis Barraza",
		"Cyber Myk Switchblade",
		"Tactical Edge",
		"Fearful Frost",
		"Blazing Charioteer",
		"Maggie's Machete",
		"Ivory Snare",
		"Blackstar",
		"Heaven's Order",
		"Golden Fang",
		"Snake Eyes",
		"Gentleman Kor",
		"First Day Asuri",
		"Eye of Elyria",
		"Evergrowth",
		"Beguiling Blades",
		"Shin Sekai Koji",
		"Rain of Fire",
		"Abyssal Goblin Mako",
		"Harvest Cleaver",
		"Golden Light",
		"Speedmetal Jhala",
		"Cyber Myk Axe",
		"Big ol' Knife",
		"Metadev Orion",
		"Dwarven-Forged Boots",
		"Switchblade",
		"Patrick Star",
		"Cryptomage Diana",
		"Isu Apple",
		"Crimson Oni Jiro",
		"Munin",
		"Blazing Fire",
		"Kill Thrill Hattori",
		"Phoenix Wings",
		"Steam Rocket",
		"Asgardian Bow",
		"Tempo Lock",
		"Atomic Sledge",
		"Lionheart Roland",
		"Abyssal Excavator",
		"Amanita Naginata",
		"Naptime",
		"Packbane",
		"Tactical Blade",
		"Disgrace",
		"Armor of Brutus Ezio",
		"DJ Ada",
		"Flamepiercer",
		"Alucard Sword",
		"Raven's Talon",
		"Sky Scourge Azoth",
		"Storm Shadow",
		"Pledge & Pride",
		"Kor in Space",
		"Four Arms",
		"Jötunn Armaments",
		"Roman Reigns",
		"Zombie Whisperer",
		"Loathsome Talon",
		"Michonne's Katana",
		"Calling Card",
		"Stuffing Spear",
		"Climbing Gear",
		"Lionguard Diana",
		"Trident of Antiquity",
		"Raphael",
		"Chorh-Gom Cuffs",
		"Tea-KO",
		"Fangwild Fawn Ember",
		"No Contest",
		"Ancestor's Flame",
		"Royal Family",
		"Survivor Diana",
		"Atlantean Sidra",
		"Vampiric Embrace",
		"Finn Sword",
		"Gnash",
		"Asgardian Axe",
		"Scepter of Salt",
		"Queen Beat Sidra",
		"All City Caspian",
		"Six of a Kind",
		"Samaritans",
		"Xianxia Lin Fei",
		"Laughing Skull",
		"Koinobori",
		"Falling Blossoms",
		"Marigold Maul",
		"Sonar Slicers",
		"Capra Thor",
		"Thumbs Down",
		"Ripple and Wave",
		"Hello Katars",
		"Ancestral Blade",
		"Naughty & Nice",
		"Soulshard",
		"Moonstone Spear",
		"Maxilli-Blasts",
		"Hammerhead Mako",
		"Spark Compressor",
		"Project-0NYX",
		"Bloodletting",
		"Heartseeker",
		"Photosynthesis Warhammer",
		"Airbender Staff",
		"Nightmare Witnesses",
		"Voice of the Snow",
		"Ancient Azoth",
		"Hardlight Blade",
		"Regal Sun Sword",
		"Reunited",
		"The Arbiter",
		"Pocket Aces",
		"Darkheart Tower",
		"Dragon's Fang",
		"Key to Your Heart",
		"Fairy Fire",
		"Crimson Pike",
		"Treble Makers",
		"Cuffed Regalia",
		"The Mixup",
		"Platinum Pike",
		"Corrupted Steps",
		"Thea",
		"Heirloom (Bow Skin)",
		"Starfall",
		"Bullhorn Basher",
		"Crafts Time",
		"Jake",
		"Sharkshooters",
		"Bo Staff",
		"Dwarven-Forged Katars",
		"Blistering Bellows",
		"The Claymores",
		"Goalie Stick",
		"Ashen Warmonger Roland",
		"Quill of Thoth",
		"Fancy Lance",
		"Commander and Chief",
		"Heart Flutter",
		"Hidden Blades",
		"Magnum Pistols",
		"Yggdrasil's Branch",
		"Zariel",
		"Wyvernbane",
		"Silver Sixshooters",
		"Jubilation Blasters",
		"Darkest Hour",
		"Derby Dusters",
		"The Don",
		"Hellboy",
		"Nightmare Knuckles",
		"The Giver's Grasp",
		"Hell's Hearts",
		"Lion's Reign",
		"Lionclaw",
		"Shot Caller",
		"Aesinite Lance",
		"Elven Battle Spear",
		"Raging Furnace",
		"Isaiah",
		"RGB Orb",
		"The Iron Flight",
		"Zuko",
		"Imperial Seals",
		"Brazen Maul",
		"Masked Hero Cassidy",
		"Sparring Gloves",
		"Lara Croft",
		"Spirit Breakers",
		"Sylvan Cleric Kaya",
		"Magma Heart",
		"Swamp Serum",
		"Shooting Star",
		"Fatal Fans",
		"Orbot",
		"Cybernetic Beat Isaiah",
		"Love Sick",
		"Sidra",
		"Knowledge is Key",
		"Devil's Hand",
		"Undying Mirage",
		"Booming Belfry",
		"Fiendish Howl",
		"Arcane Loki",
		"Cyber Myk Pistols",
		"Great Mandibles",
		"Ninetails",
		"Radiant Ember",
		"Asuri",
		"Darkheart Zariel",
		"Eivor",
		"Murder of Crows",
		"RGB Bow",
		"Poseidon's Gift",
		"Beckoning Bramble",
		"Death Jester Jaeyun",
		"Banana Guard Lance",
		"Modi",
		"Cyber Myk Sickle",
		"Dwarven-Forged Hammer",
		"Heartbreak Havoc",
		"Mirage",
		"Prickly Cut",
		"Terra Firma",
		"Crossfade Orion",
		"Tethered Plane",
		"RGB Rocket Lance",
		"Autumn Harvest",
		"Daemon Killer",
		"RGB Hammer",
		"Chainbreakers",
		"Jade Crescent",
		"Reno",
		"Glorious Deco",
		"Rick",
		"Loki",
		"Highwayman's Flintlocks",
		"Shadow Casters",
		"Heavy Hitter",
		"Axe of Might",
		"Knifebeak",
		"Pneumatic Hammer",
		"Daomadan Lin Fei",
		"Dark of Night Lucien",
		"Cyberlink Blasters",
		"Mikimoto Katana",
		"H4MM3R Time",
		"Skadi's Bow",
		"Nutcracker Cassidy",
		"Nina Williams",
		"Amplitude",
		"Rocket Parasol",
		"Pillage and Plunder",
		"Golden Lion Fang",
		"Dusk Till Dawn",
		"Stormsteel Sentinel",
		"Diamondhead",
		"Griffoth's Fire",
		"Nightmare Sword",
		"Future Spirit Artemis",
		"Burnout (Weapon Skin)",
		"Betrayal & Power",
		"Sacred Blades",
		"Speaker of the Sea",
		"Eternity",
		"Fangwild Spine",
		"Supreme Ruler Vraxx",
		"Nightmare Spine",
		"Dragon's Shine",
		"Beatdown Bell",
		"Kitsune Hattori",
		"Flora Striker",
		"Wyvern's Sting",
		"Marrow",
		"Phoenix Claw",
		"Scavenger's Spoils",
		"Dwarven-Forged Cannon",
		"Greased Lightning Koji",
		"Mogar",
		"Extra Large Scalpel",
		"Winter Daggers",
		"Owl Bard Hugin",
		"Toph",
		"Raven Claws",
		"Dual Hunting Knives",
		"Spear of Wisdom",
		"Phantom Toxin",
		"ASM Blasters",
		"Wandering Wind",
		"Geocrashers",
		"Diamond Fists",
		"Scythe of Torment",
		"Arctic Fox Yumiko",
		"Fellthorne",
		"Soul Seeker",
		"Yumiko",
		"The Singularities",
		"Tropic Breeze",
		"The Renegade",
		"Brawldog Mordex",
		"Saints & Souls",
		"La Guitarra",
		"Eldritch Bane",
		"Wheel Locks",
		"Deep Sea Lucien",
		"Bone Cleaver",
		"Stellar Nova",
		"Beachside Zariel",
		"Steamsmith Scarlet",
		"Brahma Bulls",
		"Tactical Cannon",
		"Symphonic Surge",
		"Frost Fang",
		"Nightcap Caspian",
		"Lodestone",
		"Planet Destroyer",
		"Greed and Avarice",
		"Daryl",
		"Balanced Counsel",
		"Nightblade Hattori",
		"Wenqing Lin Fei",
		"Season's Beatings",
		"Eldritch Core",
		"Vial of Crows",
		"Airship Scarlet",
		"Boots of Mercy",
		"Lightbringer",
		"Anakin Skywalker",
		"Darth Vader",
		"Obi-Wan Kenobi",
		"Ahsoka Tano",
		"Republic General's Gauntlets",
		"Jedi Training Remote",
		"Durasteel Debris",
		"Mammoth Galoshes",
		"Asgardian Lightsaber",
		"Asgardian Shoto Lightsabers",
		"Asgardian Saberstaff",
		"Hardlight Gauntlets",
		"Vivi",
		"Druid Mage Chel",
		"Gardener Bödvar",
		"Covert Ops Vivi",
		"Streetwear Vivi",
		"Grã-mestra Batista",
		"Aú Sem Mão",
		"Charmed, I'm Sure",
		"Martelo No Chão",
		"Galopante Blasts",
		"Stealthy Steps",
		"Silenced Pistols",
		"Bahian Blasters",
		"Barra Boots",
		"Cultivator's Mallet",
		"Paring Knife",
		"Earthen Striders",
		"Grasping Boughs",
		"Hardlight Orb",
		"Beach Ball",
		"Strike of the Wise",
		"Brave Magi ☆ Twinkling Justice",
		"Darth Maul",
		"Fang & Claw",
		"Hardlight Pincers",
		"Hardlight Sword",
		"Void Zenith Artemis",
		"Lakeside Loki",
		"Alepisaurus Mako",
		"Accretion Mass Projector",
		"Edge of the Universe",
		"Sharpoons",
		"Caught a Big One!",
		"Carved Lancet Teeth",
		"Great Bone Matau",
		"Hardlight Scythe"
	];

	function chunkArray(arr, chunk) {
		const result = [];
		for (let i = 0; i < arr.length; i += chunk) {
			const chunkArray = arr.slice(i, i + chunk);
			result.push(chunkArray);
		}
		return result;
	}

	pagesList = chunkArray(pagesPurge, 50);
	
	//console.log(await bot.purge(aw))

	bot.batchOperation(
		pagesList,
		(pages, idx) => {
			return Promise.race([bot.purge(pages).catch(err => console.log(err)).then(() => {done.push(pages); return sleep(3000)}), sleep(4500)]).then(e => sleep(e == "sleep" ? 10000 : 2750))
		},
		/* concurrency */ 3,
		/* retries */ 2
	).then(exit);

	interval = setInterval(() => {
		fs.writeFileSync("done.log", JSON.stringify(done))
	}, 10000)
}()